services:
  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db #points to the hostname of the db service within Docker network
      - DB_PORT=5432
      - DB_NAME=ecommerce
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD} #pull from the .env file
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@email.com
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
            python manage.py import_products &&
            python manage.py createsuperuser --noinput &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:12.19-alpine3.19
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
