services:
  django:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db #points to the hostname of the db service within Docker network
      - DB_PORT=5432
      - DB_NAME=ecommerce
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD} #pull from the .env file

    volumes:
      - .:/app
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done;
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:12.19-alpine3.19
    container_name: db
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
